"""
Broad track — MEG-XL pretrained foundation model, fine-tuned for word decoding.

  smoke        (CPU)  import brainstorm, load BioCodec + pretrained MEG-XL, 1 forward
  make_sensor_json    generate meg_sensors_information.json (Neuromag 306) once
  download_data       fetch broad subjects' h5 + events into the MEG-XL layout
  finetune     (GPU)  hydra evaluate_criss_cross_word_classification on subjects 1-12
  (submission generated by modal/broad_submit.py)

Model runs at 50 Hz; word windows are retrieval-scored against t5-large embeddings.
"""

import os
import sys
from pathlib import Path

import modal

from common import MEGXL_SRC, PNPL_SRC, VOLUMES, WORK_DIR, HF_CACHE_DIR, HF_ENV, work_vol, hf_cache

MEGXL_HF_REPO = "pnpl/MEG-XL"
MEGXL_CKPT = "meg-xl-med-v2.ckpt"

# Paths on the work volume
MEGXL_WORK = f"{WORK_DIR}/megxl"
DATA_ROOT = f"{MEGXL_WORK}/data"          # <task>/derivatives/{serialised,events}
CACHE_DIR = f"{MEGXL_WORK}/cache"         # preprocessing cache
LOG_DIR = f"{MEGXL_WORK}/logs"
SENSOR_JSON = f"{DATA_ROOT}/meg_sensors_information.json"

megxl_image = (
    modal.Image.debian_slim(python_version="3.12")
    .apt_install("git")
    .pip_install(
        "torch==2.4.1",
        "einops",
        "numpy<2.1",
        "pandas>=2.2",
        "scipy",
        "scikit-learn",
        "h5py",
        "mne>=1.4.0",
        "hydra-core>=1.3.0",
        "omegaconf>=2.3.0",
        "pytorch-lightning>=2.2",
        "transformers==4.44.2",
        "sentencepiece",
        "wandb",
        "tqdm",
        "huggingface_hub",
        "hf_transfer",
        "requests",
        extra_index_url="https://download.pytorch.org/whl/cu121",
    )
    .env({**HF_ENV, "WANDB_MODE": "offline", "WANDB_SILENT": "true",
          "TOKENIZERS_PARALLELISM": "false"})
)
if modal.is_local():
    megxl_image = (
        megxl_image
        .add_local_dir(str(PNPL_SRC), "/root/pnpl", copy=True,
                       ignore=["*.pyc", "__pycache__", ".git"])
        .add_local_dir(str(MEGXL_SRC), "/root/megxl", copy=True,
                       ignore=["*.pyc", "__pycache__", ".git", "assets"])
        .run_commands(
            "pip install --no-deps /root/pnpl",
            # The published MEG-XL checkpoint's hyper_parameters carry extra keys
            # (e.g. debug_nan_checks) the current model __init__ doesn't declare.
            # Accept + ignore unknown kwargs so `CrissCrossTransformerModule(**hparams)`
            # works across the version gap.
            "sed -i 's/        fourier_pos_dim: int = 250,/        fourier_pos_dim: int = 250,\\n        **kwargs,/' /root/megxl/brainstorm/models/criss_cross_transformer.py",
            "sed -i \"s/self.save_hyperparameters(ignore=\\['tokenizer'\\])/self.save_hyperparameters(ignore=['tokenizer'] + list(kwargs.keys()))/\" /root/megxl/brainstorm/models/criss_cross_transformer.py",
        )
        .add_local_python_source("common")
    )

app = modal.App("pnpl-broad-megxl")

BIOCODEC_CKPT = "/root/megxl/brainstorm/neuro_tokenizers/biocodec_ckpt.pt"


def _dirs():
    for p in (MEGXL_WORK, DATA_ROOT, CACHE_DIR, LOG_DIR):
        os.makedirs(p, exist_ok=True)


@app.function(image=megxl_image, volumes=VOLUMES, timeout=30 * 60)
def smoke():
    """Import brainstorm, load BioCodec + pretrained MEG-XL, run one forward."""
    sys.path.insert(0, "/root/megxl")
    import torch
    from huggingface_hub import hf_hub_download
    from brainstorm.evaluate_criss_cross_word_classification import (
        load_tokenizer, load_criss_cross_model,
    )

    dev = "cuda" if torch.cuda.is_available() else "cpu"
    print("device:", dev, "torch:", torch.__version__)

    tok = load_tokenizer(BIOCODEC_CKPT, device=dev)
    print("BioCodec loaded")

    ckpt_path = hf_hub_download(MEGXL_HF_REPO, MEGXL_CKPT)
    print("MEG-XL ckpt:", ckpt_path)
    model = load_criss_cross_model(ckpt_path, tok, device=dev)
    print("MEG-XL loaded. latent_dim:", model.latent_dim,
          "layers:", model.hparams.num_layers, "heads:", model.hparams.num_heads)

    # Dummy 1 s @ 50 Hz window with dummy sensor geometry.
    B, C, T = 1, 306, 50
    meg = torch.randn(B, C, T, device=dev)
    xyz = torch.randn(B, C, 3, device=dev) * 0.1
    abc = torch.randn(B, C, 3, device=dev)
    stypes = torch.zeros(B, C, dtype=torch.long, device=dev)
    smask = torch.ones(B, C, device=dev)
    with torch.no_grad():
        out = model(meg, xyz, abc, stypes, smask, apply_mask=False)
    feats = out["features"]
    print("features shape:", tuple(feats.shape))
    print("SMOKE OK")
    return {"features_shape": list(feats.shape), "latent_dim": int(model.latent_dim)}


@app.function(image=megxl_image, volumes=VOLUMES, timeout=60 * 60)
def make_sensor_json():
    """Generate meg_sensors_information.json for the standard Neuromag-306 layout
    from MNE's sample data (device-coord helmet geometry, same fixed geometry the
    pretrained MEG-XL expects). Verified against the LibriBrain channel set."""
    import json
    import numpy as np
    import mne
    from huggingface_hub import hf_hub_download

    _dirs()
    os.environ["MNE_DATA"] = f"{HF_CACHE_DIR}/mne_data"
    os.makedirs(os.environ["MNE_DATA"], exist_ok=True)
    mne.set_log_level("ERROR")

    sample_dir = mne.datasets.sample.data_path()
    raw = mne.io.read_raw_fif(
        f"{sample_dir}/MEG/sample/sample_audvis_raw.fif", verbose="ERROR")
    raw.pick("meg")
    print("sample MEG channels:", len(raw.ch_names))

    sensors = []
    coil_by_name = {}
    for ch in raw.info["chs"]:
        coil = int(ch["coil_type"])
        sensors.append({
            "ch_name": ch["ch_name"],
            "coil_type": coil,
            "loc": [float(x) for x in ch["loc"]],
        })
        coil_by_name[ch["ch_name"]] = coil

    # Cross-check against a real LibriBrain h5's channel_names + channel_types.
    h5 = hf_hub_download(
        "pnpl/LibriBrain2",
        "Sherlock1/derivatives/serialised/"
        "sub-1_ses-11_task-Sherlock1_run-1_proc-bads+headpos+sss+notch+bp+ds_meg.h5",
        repo_type="dataset")
    import h5py
    with h5py.File(h5, "r") as f:
        lb_names = [s.strip() for s in f.attrs["channel_names"].split(",")]
        lb_types = [s.strip() for s in f.attrs["channel_types"].split(",")]
    missing = [n for n in lb_names if n not in coil_by_name]
    print(f"LibriBrain channels: {len(lb_names)}; missing from sample: {len(missing)}")
    # verify mag/grad agreement (coil 3024 == mag)
    mism = 0
    for n, t in zip(lb_names, lb_types):
        if n in coil_by_name:
            is_mag_json = coil_by_name[n] == 3024
            is_mag_lb = (t == "mag")
            if is_mag_json != is_mag_lb:
                mism += 1
    print(f"mag/grad mismatches vs LibriBrain: {mism} (should be 0)")

    with open(SENSOR_JSON, "w") as f:
        json.dump(sensors, f)
    work_vol.commit()
    print("wrote:", SENSOR_JSON, "n_sensors:", len(sensors))
    return {"n_sensors": len(sensors), "missing": len(missing), "mismatches": mism}


@app.function(image=megxl_image, volumes=VOLUMES, timeout=2 * 60 * 60)
def download_data(subjects: int = 12):
    """Fetch broad subjects' Sherlock1 ses-11/12 h5 + events into the MEG-XL layout
    <DATA_ROOT>/Sherlock1/derivatives/{serialised,events}. Only subjects 1..12 have h5."""
    from huggingface_hub import hf_hub_download
    _dirs()
    proc = "proc-bads+headpos+sss+notch+bp+ds"
    got, missing = 0, 0
    for sub in range(1, subjects + 1):
        for ses in ("11", "12"):
            base = f"sub-{sub}_ses-{ses}_task-Sherlock1_run-1"
            files = [
                f"Sherlock1/derivatives/serialised/{base}_{proc}_meg.h5",
                f"Sherlock1/derivatives/events/{base}_events.tsv",
            ]
            for fn in files:
                try:
                    hf_hub_download("pnpl/LibriBrain2", fn, repo_type="dataset",
                                    local_dir=DATA_ROOT)
                    got += 1
                except Exception as e:
                    print("MISSING", fn, str(e)[:80]); missing += 1
    work_vol.commit()
    # report layout
    import glob
    h5s = glob.glob(f"{DATA_ROOT}/Sherlock1/derivatives/serialised/*.h5")
    evs = glob.glob(f"{DATA_ROOT}/Sherlock1/derivatives/events/*.tsv")
    print(f"downloaded {got} files ({missing} missing). h5={len(h5s)} events={len(evs)}")
    return {"h5": len(h5s), "events": len(evs), "missing": missing}


@app.local_entrypoint()
def main():
    print(smoke.remote())
