"""
Deep track — d'Ascoli contrastive brain->text-embedding baseline on Modal.

Pipeline:
  smoke_imports  (CPU)   verify the image imports + model builds + 1 forward pass
  run_training   (GPU)   data.prepare() + fit + test on subject 0 (within-subject)
  (submission is generated by modal/deep_submit.py after training)

We call Experiment.setup_run/fit/test directly (not run_grid) to bypass exca's
result caching layer and keep the run debuggable.
"""

import os
import sys
from pathlib import Path

import modal

from common import (
    DASCOLI_SRC,
    PNPL_SRC,
    hf_cache,
    work_vol,
    HF_CACHE_DIR,
    WORK_DIR,
    HF_ENV,
)

# ---------------------------------------------------------------------------
# Image: python 3.11 + torch 2.3.1 + the dascoli stack
# ---------------------------------------------------------------------------
dascoli_image = (
    modal.Image.debian_slim(python_version="3.11")
    .apt_install("build-essential", "cmake", "git")
    # One combined install with torch PINNED so no dependency upgrades it to a
    # CUDA-13 wheel. x_transformers pinned to a torch-2.3-era release (newer
    # versions require torch>=2.5). torch 2.3.1 on PyPI is already a cu121 build.
    .pip_install(
        "torch==2.3.1",
        "torchvision==0.18.1",
        # core scientific stack
        "numpy<2.1",
        "pandas>=2.2.2",
        "pyarrow",
        "scikit-learn",
        "scipy",
        "tqdm",
        "nibabel",
        "h5py",
        "pydantic>=2.5.0",
        "torchmetrics>=1.1.2",
        # MEG / BIDS
        "mne>=1.4.0",
        "mne_bids",
        # infra / caching used by neuralset
        "exca",
        "submitit",
        "cloudpickle",
        # DL extras
        "lightning==2.4.0",
        "wandb>=0.15.11",
        "x_transformers==1.32.14",
        "transformers==4.44.2",
        "sentencepiece",
        "kenlm",
        # pnpl runtime deps
        "huggingface_hub",
        "hf_transfer",
        "requests",
        extra_index_url="https://download.pytorch.org/whl/cu121",
    )
    # braindecode from git master (as pinned by neuraltrain). Pin torch in the
    # same command so braindecode's resolver can't drag it forward.
    .pip_install(
        "braindecode@git+https://github.com/braindecode/braindecode@master",
        "torch==2.3.1",
        extra_index_url="https://download.pytorch.org/whl/cu121",
    )
    .env({**HF_ENV, "WANDB_MODE": "offline", "WANDB_SILENT": "true",
          "TOKENIZERS_PARALLELISM": "false"})
    .add_local_python_source("common")
    # copy source trees
    .add_local_dir(str(PNPL_SRC), "/root/pnpl", copy=True,
                   ignore=["*.pyc", "__pycache__", ".git"])
    .add_local_dir(str(DASCOLI_SRC), "/root/dascoli", copy=True,
                   ignore=["*.pyc", "__pycache__", ".git", "runs", "*.ckpt"])
    # install the local packages (deps already present -> --no-deps)
    .run_commands(
        "pip install --no-deps -e /root/pnpl",
        "pip install --no-deps -e /root/dascoli/neuralset",
        "pip install --no-deps -e /root/dascoli/neuraltrain",
        # main.py imports WandbLogger from the standalone pytorch_lightning
        # namespace; we only ship the `lightning` package. Same class, so point
        # the import at lightning.pytorch to avoid a second lightning distro.
        "sed -i 's/from pytorch_lightning.loggers import WandbLogger/from lightning.pytorch.loggers import WandbLogger/' /root/dascoli/sentence_decoding/main.py",
    )
)

app = modal.App("pnpl-deep-dascoli")

# Paths on the work volume
DASCOLI_WORK = f"{WORK_DIR}/dascoli"
SAVEPATH = DASCOLI_WORK
DATAPATH = f"{DASCOLI_WORK}/data"
LIBRIBRAIN100_PATH = f"{DATAPATH}/LibriBrain100"

RUN_ENV = {
    "SAVEPATH": SAVEPATH,
    "DATAPATH": DATAPATH,
    "LIBRIBRAIN100_PATH": LIBRIBRAIN100_PATH,
}


def _ensure_dirs():
    for p in (SAVEPATH, DATAPATH, LIBRIBRAIN100_PATH,
              f"{SAVEPATH}/cache", f"{SAVEPATH}/results"):
        os.makedirs(p, exist_ok=True)


@app.function(image=dascoli_image, timeout=20 * 60)
def smoke_imports():
    """Cheap CPU check: everything imports, model builds, forward runs."""
    sys.path.insert(0, "/root/dascoli")
    import torch

    import neuralset  # noqa
    import neuraltrain  # noqa
    import pnpl  # noqa
    from pnpl.competition import PRIMARY_VOCAB
    print("pnpl vocab:", len(PRIMARY_VOCAB))

    # import the training entry points
    from sentence_decoding.main import Experiment  # noqa
    from sentence_decoding.grids.defaults import default_config
    from sentence_decoding.grids.libribrain100 import (
        updated_config, LIBRIBRAIN100_50_WORD_VOCABULARY,
    )
    print("grid vocab size:", len(LIBRIBRAIN100_50_WORD_VOCABULARY))
    print("default duration:", default_config["data"]["duration"])

    # Build the brain model + transformer at the real dims and run a forward.
    from neuraltrain.models import __dict__ as _m  # noqa
    from sentence_decoding.main import ModelConfig
    bm_cfg = ModelConfig(**default_config["brain_model_config"])
    tr_cfg = ModelConfig(**default_config["transformer_config"])
    brain_model = bm_cfg.build(n_in_channels=306, n_outputs=1024)
    transformer = tr_cfg.build(dim=1024)
    n_params = sum(p.numel() for p in brain_model.parameters())
    n_params_tr = sum(p.numel() for p in transformer.parameters())
    print(f"brain_model params: {n_params/1e6:.1f}M  transformer params: {n_params_tr/1e6:.1f}M")

    B, C, T = 4, 306, 50   # 1 s @ 50 Hz
    x = torch.randn(B, C, T)
    subject_ids = torch.zeros(B, dtype=torch.long)
    channel_positions = torch.rand(B, C, 2)
    with torch.no_grad():
        y = brain_model(x, subject_ids, channel_positions)
    print("brain_model output:", tuple(y.shape))
    assert y.shape == (B, 1024), y.shape

    # SigLip loss builds
    from sentence_decoding.main import LossConfig
    loss = LossConfig(**default_config["loss"]).build()
    print("loss:", type(loss).__name__)
    print("SMOKE OK")
    return {"brain_params_M": n_params / 1e6, "ok": True}


@app.function(
    image=dascoli_image,
    gpu="L4",
    volumes=VOLUMES,
    timeout=12 * 60 * 60,
    memory=32 * 1024,
)
def run_training(n_epochs: int = 50, duration: float = 1.0, fast_dev_run: bool = False,
                 batch_size: int = 128):
    """data.prepare() (download + preprocess + t5 embeddings) then fit + test.

    We call setup_run/fit/test directly to bypass exca's @infra.apply result cache.
    """
    # env vars are read at import time by the grid/defaults modules -> set first.
    os.environ.update(RUN_ENV)
    _ensure_dirs()
    sys.path.insert(0, "/root/dascoli")

    import glob
    import torch
    from neuraltrain.utils import update_config
    from sentence_decoding.grids.libribrain100 import updated_config
    from sentence_decoding.main import Experiment

    print("CUDA available:", torch.cuda.is_available(),
          torch.cuda.get_device_name(0) if torch.cuda.is_available() else "")

    # Drop sentence-decoding retrieval metrics (BLEU/WER/BERTScore) that need the
    # LM decoder; keep only the word-retrieval Rank/TopkAcc used for BAcc@10.
    retrieval_metrics = [
        m for m in updated_config["retrieval_metrics"]
        if m["name"] in ("Rank", "TopkAcc")
    ]

    overrides = {
        "data.duration": duration,
        "data.batch_size": batch_size,
        "data.feature.device": "cuda",
        "data.num_workers": 6,
        "retrieval_metrics": retrieval_metrics,
        "trainer_config.n_epochs": n_epochs,
        "trainer_config.fast_dev_run": fast_dev_run,
    }
    config = update_config(updated_config, overrides)
    print("duration:", config["data"]["duration"], "batch:", config["data"]["batch_size"],
          "n_epochs:", config["trainer_config"]["n_epochs"], "fast_dev:", fast_dev_run)

    exp = Experiment(**config)
    print("infra.folder:", exp.infra.folder)

    loaders = exp.setup_run()
    print("loaders ready. train batches:", len(loaders["train"]))

    exp.fit(loaders["train"], loaders["val"])
    if not fast_dev_run:
        exp.test(loaders["test"])

    work_vol.commit()

    # Report metrics + locate checkpoints.
    metrics = {k: float(v) for k, v in exp._trainer.callback_metrics.items()
               if "acc" in k or "rank" in k or "loss" in k}
    ckpts = sorted(glob.glob(f"{SAVEPATH}/results/**/best.ckpt", recursive=True) +
                   glob.glob(f"{SAVEPATH}/results/**/last.ckpt", recursive=True))
    print("checkpoints:", ckpts)
    print("metrics:", metrics)
    return {"metrics": metrics, "checkpoints": ckpts}


@app.function(image=dascoli_image, volumes=VOLUMES, timeout=30 * 60)
def list_results():
    """Inspect what's on the work volume (checkpoints, caches, config)."""
    import glob
    out = {}
    for pat in ("best.ckpt", "last.ckpt", "config.yaml"):
        out[pat] = sorted(glob.glob(f"{SAVEPATH}/**/{pat}", recursive=True))
    # rough sizes
    sizes = {}
    for d in (SAVEPATH, DATAPATH, LIBRIBRAIN100_PATH):
        total = 0
        for p in glob.glob(f"{d}/**/*", recursive=True):
            try:
                total += os.path.getsize(p)
            except OSError:
                pass
        sizes[d] = round(total / 1e9, 2)
    out["sizes_GB"] = sizes
    print(out)
    return out


@app.local_entrypoint()
def main():
    print(smoke_imports.remote())
