"""
Deep track — d'Ascoli contrastive brain->text-embedding baseline on Modal.

Pipeline:
  smoke_imports  (CPU)   verify the image imports + model builds + 1 forward pass
  run_training   (GPU)   data.prepare() + fit + test on subject 0 (within-subject)
  (submission is generated by modal/deep_submit.py after training)

We call Experiment.setup_run/fit/test directly (not run_grid) to bypass exca's
result caching layer and keep the run debuggable.
"""

import os
import sys
from pathlib import Path

import modal

from common import (
    DASCOLI_SRC,
    PNPL_SRC,
    hf_cache,
    work_vol,
    VOLUMES,
    HF_CACHE_DIR,
    WORK_DIR,
    HF_ENV,
)

# ---------------------------------------------------------------------------
# Image: python 3.11 + torch 2.3.1 + the dascoli stack
# ---------------------------------------------------------------------------
dascoli_image = (
    modal.Image.debian_slim(python_version="3.11")
    .apt_install("build-essential", "cmake", "git")
    # One combined install with torch PINNED so no dependency upgrades it to a
    # CUDA-13 wheel. x_transformers pinned to a torch-2.3-era release (newer
    # versions require torch>=2.5). torch 2.3.1 on PyPI is already a cu121 build.
    .pip_install(
        "torch==2.3.1",
        "torchvision==0.18.1",
        # core scientific stack
        "numpy<2.1",
        "pandas>=2.2.2",
        "pyarrow",
        "scikit-learn",
        "scipy",
        "tqdm",
        "nibabel",
        "h5py",
        "pydantic>=2.5.0",
        "torchmetrics>=1.1.2",
        # MEG / BIDS
        "mne>=1.4.0",
        "mne_bids",
        # infra / caching used by neuralset
        "exca",
        "submitit",
        "cloudpickle",
        # DL extras
        "lightning==2.4.0",
        "wandb>=0.15.11",
        "x_transformers==1.32.14",
        "transformers==4.44.2",
        "sentencepiece",
        "kenlm",
        # pnpl runtime deps
        "huggingface_hub",
        "hf_transfer",
        "requests",
        extra_index_url="https://download.pytorch.org/whl/cu121",
    )
    # braindecode from git master (as pinned by neuraltrain). Pin torch AND
    # torchaudio in the same command: braindecode pulls torchaudio, whose latest
    # wheel is a CUDA-13 build (libcudart.so.13) incompatible with our cu121 torch.
    .pip_install(
        "braindecode@git+https://github.com/braindecode/braindecode@master",
        "torch==2.3.1",
        "torchaudio==2.3.1",
        extra_index_url="https://download.pytorch.org/whl/cu121",
    )
    .env({**HF_ENV, "WANDB_MODE": "offline", "WANDB_SILENT": "true",
          "TOKENIZERS_PARALLELISM": "false"})
)

# Local-only build steps (copy source, install editable, patch import). Guarded
# so re-importing this module inside a container doesn't touch host paths.
if modal.is_local():
    dascoli_image = (
        dascoli_image
        # copy source trees (copy=True so subsequent build steps can use them)
        .add_local_dir(str(PNPL_SRC), "/root/pnpl", copy=True,
                       ignore=["*.pyc", "__pycache__", ".git"])
        .add_local_dir(str(DASCOLI_SRC), "/root/dascoli", copy=True,
                       ignore=["*.pyc", "__pycache__", ".git", "runs", "*.ckpt"])
        .run_commands(
            # Non-editable installs: packages land in site-packages, avoiding the
            # namespace-package collision between the copied /root/dascoli/{neuralset,
            # neuraltrain} project dirs and `import neuralset`/`import neuraltrain`.
            # Only /root/dascoli/sentence_decoding is imported from the source tree.
            "pip install --no-deps /root/pnpl",
            "pip install --no-deps /root/dascoli/neuralset",
            "pip install --no-deps /root/dascoli/neuraltrain",
            # main.py imports WandbLogger from standalone pytorch_lightning; we
            # ship only `lightning`. Same class -> repoint to lightning.pytorch.
            "sed -i 's/from pytorch_lightning.loggers import WandbLogger/from lightning.pytorch.loggers import WandbLogger/' /root/dascoli/sentence_decoding/main.py",
            # The offline WandbLogger returns save_dir=None; the TestRetrieval
            # callback writes retrieval_outputs/decoded_sentences there. Fall back
            # to $SAVEPATH so it doesn't crash on os.path.join(None, ...).
            "sed -i 's#trainer.logger.save_dir#(trainer.logger.save_dir or __import__(\"os\").environ.get(\"SAVEPATH\", \"/tmp\"))#g' /root/dascoli/sentence_decoding/callbacks.py",
            # InitialEvaluation runs a val loop before training. Under Lightning's
            # default inference_mode, the model's LazyLinear params materialize as
            # *inference tensors* that then can't be used in the training backward
            # ("Inference tensors cannot be saved for backward"). inference_mode=False
            # makes eval use no_grad instead, so params stay normal tensors.
            "sed -i 's/gradient_clip_val=self.trainer_config.gradient_clip_val,/gradient_clip_val=self.trainer_config.gradient_clip_val, inference_mode=False,/' /root/dascoli/sentence_decoding/main.py",
        )
        # add_local_* must be the LAST build steps (mounted on container start).
        .add_local_python_source("common")
    )

app = modal.App("pnpl-deep-dascoli")

# Paths on the work volume
DASCOLI_WORK = f"{WORK_DIR}/dascoli"
SAVEPATH = DASCOLI_WORK
DATAPATH = f"{DASCOLI_WORK}/data"
LIBRIBRAIN100_PATH = f"{DATAPATH}/LibriBrain100"

RUN_ENV = {
    "SAVEPATH": SAVEPATH,
    "DATAPATH": DATAPATH,
    "LIBRIBRAIN100_PATH": LIBRIBRAIN100_PATH,
}


def _ensure_dirs():
    for p in (SAVEPATH, DATAPATH, LIBRIBRAIN100_PATH,
              f"{SAVEPATH}/cache", f"{SAVEPATH}/results"):
        os.makedirs(p, exist_ok=True)


@app.function(image=dascoli_image, timeout=20 * 60)
def smoke_imports():
    """Cheap CPU check: everything imports, model builds, forward runs."""
    # env is read at import time by defaults.py -> set before importing the grid.
    for k, v in {"SAVEPATH": "/tmp/sp", "DATAPATH": "/tmp/dp",
                 "LIBRIBRAIN100_PATH": "/tmp/dp/LibriBrain100"}.items():
        os.environ[k] = v
    for p in ("/tmp/sp/cache", "/tmp/sp/results", "/tmp/dp", "/tmp/dp/LibriBrain100"):
        os.makedirs(p, exist_ok=True)
    sys.path.append("/root/dascoli")
    import torch

    import neuralset  # noqa
    import neuraltrain  # noqa
    import pnpl  # noqa
    from pnpl.competition import PRIMARY_VOCAB
    print("pnpl vocab:", len(PRIMARY_VOCAB))

    # import the training entry points
    from neuraltrain.utils import update_config
    from sentence_decoding.main import Experiment  # noqa
    from sentence_decoding.grids.defaults import default_config
    from sentence_decoding.grids.libribrain100 import (
        updated_config, LIBRIBRAIN100_50_WORD_VOCABULARY,
    )
    print("grid vocab size:", len(LIBRIBRAIN100_50_WORD_VOCABULARY))
    print("default duration:", default_config["data"]["duration"])

    # Validate the whole config via pydantic (the real training entry path).
    cfg = update_config(updated_config, {
        "infra.workdir": None,
        "retrieval_metrics": [m for m in updated_config["retrieval_metrics"]
                              if m["name"] in ("Rank", "TopkAcc")],
    })
    exp = Experiment(**cfg)
    print("Experiment built OK; infra.folder:", exp.infra.folder)

    # Build the brain model + transformer at the real dims and run a forward.
    # ModelConfig is a discriminated Union alias, so use the concrete classes.
    from neuraltrain.models import SimpleConvTimeAggConfig, TransformerEncoderConfig
    bm_cfg = SimpleConvTimeAggConfig(**default_config["brain_model_config"])
    tr_cfg = TransformerEncoderConfig(**default_config["transformer_config"])
    brain_model = bm_cfg.build(n_in_channels=306, n_outputs=1024)
    transformer = tr_cfg.build(dim=1024)

    # Forward first (LazyModules initialize their params on first forward).
    B, C, T = 4, 306, 50   # 1 s @ 50 Hz
    x = torch.randn(B, C, T)
    subject_ids = torch.zeros(B, dtype=torch.long)
    channel_positions = torch.rand(B, C, 2)
    with torch.no_grad():
        y = brain_model(x, subject_ids, channel_positions)
    print("brain_model output:", tuple(y.shape))
    assert y.shape == (B, 1024), y.shape

    def _count(m):
        try:
            return sum(p.numel() for p in m.parameters())
        except ValueError:
            return -1  # still has uninitialized lazy params (not forwarded)
    print(f"brain_model params: {_count(brain_model)/1e6:.1f}M  "
          f"transformer params (may be lazy): {_count(transformer)/1e6:.1f}M")

    # SigLip loss builds
    from sentence_decoding.main import LossConfig
    loss = LossConfig(**default_config["loss"]).build()
    print("loss:", type(loss).__name__)
    print("SMOKE OK")
    return {"brain_params_M": n_params / 1e6, "ok": True}


@app.function(
    image=dascoli_image,
    gpu="L4",
    volumes=VOLUMES,
    timeout=12 * 60 * 60,
    memory=32 * 1024,
)
def run_training(n_epochs: int = 50, duration: float = 1.0, fast_dev_run: bool = False,
                 batch_size: int = 128):
    """data.prepare() (download + preprocess + t5 embeddings) then fit + test.

    We call setup_run/fit/test directly to bypass exca's @infra.apply result cache.
    """
    # env vars are read at import time by the grid/defaults modules -> set first.
    os.environ.update(RUN_ENV)
    _ensure_dirs()
    sys.path.append("/root/dascoli")

    import glob
    import torch
    from neuraltrain.utils import update_config
    from sentence_decoding.grids.libribrain100 import updated_config
    from sentence_decoding.main import Experiment

    print("CUDA available:", torch.cuda.is_available(),
          torch.cuda.get_device_name(0) if torch.cuda.is_available() else "")

    # Drop sentence-decoding retrieval metrics (BLEU/WER/BERTScore) that need the
    # LM decoder; keep only the word-retrieval Rank/TopkAcc used for BAcc@10.
    retrieval_metrics = [
        m for m in updated_config["retrieval_metrics"]
        if m["name"] in ("Rank", "TopkAcc")
    ]

    overrides = {
        "data.duration": duration,
        "data.batch_size": batch_size,
        "data.feature.device": "cuda",
        "data.num_workers": 6,
        "retrieval_metrics": retrieval_metrics,
        "trainer_config.n_epochs": n_epochs,
        "trainer_config.fast_dev_run": fast_dev_run,
        # exca's WorkDir would require neuralset/neuraltrain to be *editable*
        # installs (for copying source to remote workers). We run locally
        # (cluster=None) and bypass @infra.apply, so drop the copied packages.
        "infra.workdir": None,
    }
    config = update_config(updated_config, overrides)
    print("duration:", config["data"]["duration"], "batch:", config["data"]["batch_size"],
          "n_epochs:", config["trainer_config"]["n_epochs"], "fast_dev:", fast_dev_run)

    exp = Experiment(**config)
    print("infra.folder:", exp.infra.folder)

    loaders = exp.setup_run()
    print("loaders ready. train batches:", len(loaders["train"]))

    # Save the constant channel-position montage (306,2) + subject id for the
    # submission script (the model needs channel_positions at inference).
    import numpy as np
    _sb = next(iter(loaders["train"]))
    np.savez(
        f"{SAVEPATH}/submission_assets.npz",
        channel_positions=_sb.data["channel_positions"][0].cpu().numpy(),
        subject_id=_sb.data["subject_id"][0].cpu().numpy(),
        neuro_shape=np.array(list(_sb.data["neuro"].shape)),
    )
    print("saved submission_assets.npz; neuro shape:", tuple(_sb.data["neuro"].shape))
    work_vol.commit()

    exp.fit(loaders["train"], loaders["val"])
    if not fast_dev_run:
        exp.test(loaders["test"])

    work_vol.commit()

    # Report metrics + locate checkpoints.
    metrics = {k: float(v) for k, v in exp._trainer.callback_metrics.items()
               if "acc" in k or "rank" in k or "loss" in k}
    ckpts = sorted(glob.glob(f"{SAVEPATH}/results/**/best.ckpt", recursive=True) +
                   glob.glob(f"{SAVEPATH}/results/**/last.ckpt", recursive=True))
    print("checkpoints:", ckpts)
    print("metrics:", metrics)
    return {"metrics": metrics, "checkpoints": ckpts}


@app.function(image=dascoli_image, volumes=VOLUMES, timeout=30 * 60)
def list_results():
    """Inspect what's on the work volume (checkpoints, caches, config)."""
    import glob
    out = {}
    for pat in ("best.ckpt", "last.ckpt", "config.yaml"):
        out[pat] = sorted(glob.glob(f"{SAVEPATH}/**/{pat}", recursive=True))
    # rough sizes
    sizes = {}
    for d in (SAVEPATH, DATAPATH, LIBRIBRAIN100_PATH):
        total = 0
        for p in glob.glob(f"{d}/**/*", recursive=True):
            try:
                total += os.path.getsize(p)
            except OSError:
                pass
        sizes[d] = round(total / 1e9, 2)
    out["sizes_GB"] = sizes
    print(out)
    return out


@app.local_entrypoint()
def main():
    print(smoke_imports.remote())
